# Generated by Django 6.0.4 on 2026-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_time_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
