# Generated by Django 6.0.4 on 2026-05-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_category_options_category_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional pen name. Shown on your stories instead of your real name.', max_length=60, null=True, unique=True),
        ),
    ]
