# Generated by Django 6.0.4 on 2026-05-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_tag_story_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
