# Generated by Django 6.0.4 on 2026-05-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_story_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('original', 'Original'), ('retelling', 'Retelling'), ('adaptation', 'Adaptation')], default='original', max_length=10),
        ),
    ]
